operationsMappings:
  notEmpty:
    operationCall: io.github.indesil.beren.operations.Operations.notEmpty(this)
    defaultMessage: "This %{paramName} should not be empty! Where is it!? Where are you my precious!?"