operationsMappings:
  neitherOf(a):
    operationCall: pl.jlabs.beren.operations.Operations.neitherOf(this, a)
    defaultMessage: "%{paramName} must be neither of %{a}"
  greaterThan(var):
    operationCall: pl.jlabs.beren.operations.Operations.greaterThan(this, var)
    defaultMessage: "%{paramName} must be bigger than %{var}"
  between(a,b):
    operationCall: pl.jlabs.beren.operations.Operations.between(this, a, b)
    defaultMessage: "%{paramName} must be between %{a} and %{b}"
  notNull:
    operationCall: java.util.Objects.nonNull(this)
    defaultMessage: "%{paramName} must not be null!"
  notEmpty:
    operationCall: org.apache.commons.lang3.StringUtils.isNotEmpty(this)
    defaultMessage: "%{paramName} must not be empty"